# Generated by Django 4.2 on 2023-04-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Certifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                (
                    "institutions",
                    models.CharField(max_length=100, verbose_name="Institutions"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="Inst", verbose_name="Image"
                    ),
                ),
                ("url", models.URLField()),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creation"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now_add=True, verbose_name="Updated"),
                ),
            ],
            options={
                "verbose_name": "Cerfications",
                "verbose_name_plural": "Cerficationss",
            },
        ),
    ]
