# Generated by Django 4.2 on 2023-04-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Library",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="logos", verbose_name="Image"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Icon"
                    ),
                ),
            ],
            options={
                "verbose_name": "Library",
                "verbose_name_plural": "Libraries",
                "db_table": "Library",
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Language")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="skills", verbose_name="Image"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Icon"
                    ),
                ),
                ("library", models.ManyToManyField(to="skills.library")),
            ],
            options={
                "verbose_name": "Language",
                "verbose_name_plural": "Languages",
                "db_table": "Language",
            },
        ),
    ]
